server:
  port: 9001
spring:
  rabbitmq:
    addresses: localhost:5672

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dispatch?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  session:
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER